from __future__ import annotations

from pathlib import Path
from typing import Dict, Iterable, List

import pandas as pd


OUTPUT_SCHEMAS: Dict[str, List[str]] = {
    "model_leaderboard.csv": [
        "run_id",
        "generated_at",
        "horizon",
        "window_type",
        "is_official",
        "model",
        "rank",
        "test_start",
        "test_end",
        "sample_count",
        "directional_accuracy",
        "balanced_accuracy",
        "brier_score",
        "calibration_error",
        "mae",
        "rmse",
        "sharpe",
        "max_drawdown",
        "num_trades",
        "turnover",
        "tc_adjusted_return",
        "beats_buy_hold_direction",
        "beats_momentum_30d",
        "beats_momentum_90d",
        "beats_random_baseline",
        "useful_model",
        "reliability_label",
        "selection_eligible",
        "notes",
    ],
    "backtest_summary.csv": [
        "run_id",
        "horizon",
        "window_type",
        "is_official",
        "model",
        "test_start",
        "test_end",
        "sample_count",
        "threshold",
        "threshold_source",
        "directional_accuracy",
        "balanced_accuracy",
        "brier_score",
        "calibration_error",
        "mae",
        "rmse",
        "gross_return",
        "tc_adjusted_return",
        "transaction_cost_bps",
        "sharpe",
        "max_drawdown",
        "num_trades",
        "turnover",
        "buy_hold_directional_accuracy",
        "buy_hold_tc_adjusted_return",
        "momentum_30d_directional_accuracy",
        "momentum_30d_tc_adjusted_return",
        "momentum_90d_directional_accuracy",
        "momentum_90d_tc_adjusted_return",
        "random_directional_accuracy",
        "random_tc_adjusted_return",
        "beats_buy_hold_direction",
        "beats_momentum_30d",
        "beats_momentum_90d",
        "beats_random_baseline",
        "useful_model",
        "reliability_label",
        "selection_eligible",
        "notes",
    ],
    "equity_curves.csv": [
        "run_id",
        "date",
        "horizon",
        "window_type",
        "model",
        "signal",
        "position",
        "asset_return",
        "btc_return",
        "gross_strategy_return",
        "tc_adjusted_strategy_return",
        "equity_gross",
        "equity_tc_adjusted",
        "equity_buy_hold",
        "trade_flag",
        "turnover",
    ],
    "calibration_table.csv": [
        "run_id",
        "horizon",
        "window_type",
        "model",
        "prob_bin_low",
        "prob_bin_high",
        "sample_count",
        "avg_predicted_prob",
        "actual_up_rate",
        "brier_score",
        "calibration_error",
        "probability_confidence",
    ],
    "confidence_intervals.csv": [
        "run_id",
        "horizon",
        "window_type",
        "model",
        "metric",
        "estimate",
        "ci_low",
        "ci_high",
        "ci_method",
        "permutation_p_value",
        "bootstrap_iterations",
        "sample_count",
    ],
    "regime_slices.csv": [
        "run_id",
        "horizon",
        "window_type",
        "model",
        "regime_name",
        "regime_value",
        "sample_count",
        "directional_accuracy",
        "balanced_accuracy",
        "brier_score",
        "calibration_error",
        "sharpe",
        "max_drawdown",
        "tc_adjusted_return",
        "beats_baselines",
        "stable_regime_result",
    ],
    "latest_forecast.csv": [
        "run_id",
        "generated_at",
        "as_of_date",
        "horizon",
        "model",
        "selected_model",
        "selection_reason",
        "current_price",
        "predicted_direction",
        "signal",
        "predicted_probability_up",
        "probability_confidence",
        "expected_return",
        "model_implied_forecast_price",
        "reliability_label",
        "is_primary_objective",
        "is_secondary_objective",
        "is_diagnostic",
    ],
    "latest_signal_interpretation.csv": [
        "run_id",
        "generated_at",
        "as_of_date",
        "asset_id",
        "horizon",
        "selected_model",
        "selected_feature_set",
        "strategy_action",
        "risk_label",
        "probability_up",
        "expected_return",
        "long_threshold",
        "expected_return_threshold",
        "risk_off_threshold",
        "active_signal_count",
        "active_coverage",
        "risk_off_bucket_count",
        "risk_off_bucket_avg_return",
        "signal_policy_promoted",
        "asset_feature_set_promoted",
        "reliability_label",
        "reason",
    ],
    "data_availability.csv": [
        "run_id",
        "generated_at",
        "source",
        "endpoint",
        "dataset",
        "status",
        "requested_fields",
        "available_fields",
        "rows",
        "first_date",
        "last_date",
        "failure_reason",
        "is_used_in_model",
        "revision_warning",
    ],
    "feature_audit.csv": [
        "feature_name",
        "source",
        "raw_metric",
        "transform",
        "lag_days",
        "release_delay_days",
        "first_date",
        "last_date",
        "missing_pct",
        "used_in_model",
    ],
}

DIAGNOSTIC_OUTPUT_SCHEMAS: Dict[str, List[str]] = {
    "model_rejection_reasons.csv": [
        "run_id",
        "horizon",
        "window_type",
        "model_name",
        "is_baseline",
        "n_samples",
        "directional_accuracy",
        "beats_buy_hold",
        "beats_momentum_30d",
        "beats_momentum_90d",
        "beats_random_baseline",
        "passes_transaction_cost_check",
        "passes_calibration_check",
        "passes_sample_threshold",
        "passes_reliability_check",
        "final_rejection_reason",
    ],
    "feature_signal_diagnostics.csv": [
        "run_id",
        "feature_name",
        "source",
        "feature_group",
        "horizon",
        "window_type",
        "n_samples",
        "pearson_corr",
        "spearman_corr",
        "information_coefficient",
        "ic_t_stat",
        "ic_p_value",
        "missing_pct",
        "first_date",
        "last_date",
        "direction",
        "notes",
    ],
    "feature_group_ablation.csv": [
        "run_id",
        "horizon",
        "window_type",
        "feature_group",
        "model_name",
        "n_features",
        "n_samples",
        "directional_accuracy",
        "balanced_accuracy",
        "brier_score",
        "calibration_error",
        "sharpe",
        "max_drawdown",
        "net_return",
        "beats_buy_hold",
        "beats_momentum",
        "reliability_label",
    ],
    "model_regime_breakdown.csv": [
        "run_id",
        "horizon",
        "window_type",
        "model_name",
        "regime",
        "n_samples",
        "directional_accuracy",
        "net_return",
        "sharpe",
        "max_drawdown",
        "reliability_label",
    ],
    "derivatives_coverage.csv": [
        "run_id",
        "source",
        "metric",
        "status",
        "rows",
        "first_date",
        "last_date",
        "missing_pct",
        "used_in_model",
        "failure_reason",
    ],
    "derivatives_impact.csv": [
        "run_id",
        "horizon",
        "window_type",
        "model_name",
        "derivatives_included",
        "n_features",
        "n_samples",
        "directional_accuracy",
        "balanced_accuracy",
        "brier_score",
        "calibration_error",
        "sharpe",
        "max_drawdown",
        "net_return",
        "beats_buy_hold",
        "beats_momentum_30d",
        "beats_momentum_90d",
        "reliability_label",
    ],
    "feature_group_stability.csv": [
        "run_id",
        "feature_group",
        "model_name",
        "horizon",
        "window_type",
        "period_slice",
        "n_samples",
        "directional_accuracy",
        "net_return",
        "sharpe",
        "max_drawdown",
        "reliability_label",
    ],
    "polymarket_coverage.csv": [
        "run_id",
        "asset_id",
        "source",
        "status",
        "rows",
        "events",
        "markets",
        "first_date",
        "last_date",
        "missing_pct",
        "used_in_model",
        "failure_reason",
    ],
    "polymarket_feature_diagnostics.csv": [
        "run_id",
        "asset_id",
        "feature_name",
        "horizon",
        "window_type",
        "n_samples",
        "coverage_pct",
        "pearson_corr",
        "spearman_corr",
        "information_coefficient",
        "ic_t_stat",
        "ic_p_value",
        "first_date",
        "last_date",
        "used_in_official_model",
        "notes",
    ],
    "polymarket_impact.csv": [
        "run_id",
        "asset_id",
        "horizon",
        "window_type",
        "model_name",
        "polymarket_included",
        "n_features",
        "n_polymarket_features",
        "n_samples",
        "directional_accuracy",
        "balanced_accuracy",
        "brier_score",
        "calibration_error",
        "sharpe",
        "max_drawdown",
        "net_return",
        "beats_buy_hold",
        "beats_momentum_30d",
        "beats_momentum_90d",
        "beats_random_baseline",
        "reliability_label",
        "passes_official_gates",
    ],
    "factor_quality_scorecard.csv": [
        "run_id",
        "asset_id",
        "feature_name",
        "feature_group",
        "source",
        "horizon",
        "window_type",
        "n_samples",
        "coverage_pct",
        "information_coefficient",
        "ic_p_value",
        "ic_sign",
        "ic_stability_score",
        "missing_pct",
        "correlation_cluster",
        "keep_candidate",
        "drop_reason",
    ],
    "signal_quality_report.csv": [
        "run_id",
        "asset_id",
        "horizon",
        "window_type",
        "candidate_feature_set",
        "model_name",
        "n_samples",
        "n_long_signals",
        "n_neutral_signals",
        "abstention_rate",
        "long_hit_rate",
        "long_avg_return",
        "false_positive_rate",
        "avg_probability_when_long",
        "realized_return_when_long",
        "brier_score",
        "calibration_error",
        "net_return",
        "bootstrap_ci_low",
        "bootstrap_ci_high",
        "permutation_p_value",
        "reliability_label",
    ],
    "pruned_feature_leaderboard.csv": [
        "run_id",
        "asset_id",
        "horizon",
        "window_type",
        "candidate_feature_set",
        "model_name",
        "n_features",
        "median_selected_features",
        "n_samples",
        "directional_accuracy",
        "balanced_accuracy",
        "brier_score",
        "calibration_error",
        "sharpe",
        "max_drawdown",
        "net_return",
        "beats_buy_hold",
        "beats_momentum_30d",
        "beats_momentum_90d",
        "beats_random_baseline",
        "selection_eligible",
        "promotion_eligible",
        "reliability_label",
        "window_fingerprint",
        "rejection_reason",
    ],
    "feature_pruning_report.csv": [
        "run_id",
        "asset_id",
        "horizon",
        "window_type",
        "candidate_feature_set",
        "model_name",
        "n_samples",
        "official_30d_accuracy",
        "brier_score",
        "calibration_error",
        "net_return",
        "max_drawdown",
        "improvement_vs_all_features_accuracy",
        "improvement_vs_all_features_net_return",
        "beats_baselines",
        "bootstrap_ci_low",
        "bootstrap_ci_high",
        "permutation_p_value",
        "promotion_decision",
        "rejection_reason",
        "reliability_label",
        "report_label",
    ],
    "sol_stability_report.csv": [
        "run_id",
        "asset_id",
        "candidate_feature_set",
        "model_name",
        "period_slice",
        "n_samples",
        "directional_accuracy",
        "brier_score",
        "calibration_error",
        "net_return",
        "sharpe",
        "max_drawdown",
        "bootstrap_ci_low",
        "bootstrap_ci_high",
        "permutation_p_value",
        "reliability_label",
        "passes_stability_check",
    ],
    "signal_policy_report.csv": [
        "run_id",
        "asset_id",
        "horizon",
        "window_type",
        "candidate_feature_set",
        "model_name",
        "n_samples",
        "policy_source",
        "long_threshold_median",
        "expected_return_min_median",
        "threshold_050_used",
        "threshold_050_diagnostic_only",
        "active_signal_count",
        "active_coverage",
        "abstention_rate",
        "active_hit_rate",
        "missed_up_month_rate",
        "after_cost_return",
        "max_drawdown",
        "bootstrap_ci_low",
        "bootstrap_ci_high",
        "permutation_p_value",
        "risk_off_count",
        "risk_off_rate",
        "risk_off_hit_rate",
        "risk_off_avg_return",
        "risk_off_probability_threshold_median",
        "valid_signal_policy",
        "high_confidence_policy_eligible",
        "promoted_signal_policy",
        "rejection_reason",
    ],
    "asset_feature_set_leaderboard.csv": [
        "run_id",
        "asset_id",
        "horizon",
        "window_type",
        "candidate_feature_set",
        "model_name",
        "feature_selection_method",
        "n_features",
        "n_samples",
        "directional_accuracy",
        "balanced_accuracy",
        "brier_score",
        "calibration_error",
        "sharpe",
        "max_drawdown",
        "net_return",
        "beats_buy_hold",
        "beats_momentum_30d",
        "beats_momentum_90d",
        "beats_random_baseline",
        "beats_current_reference",
        "material_worsening",
        "regime_stability_pass",
        "bootstrap_ci_low",
        "bootstrap_ci_high",
        "permutation_p_value",
        "promotion_eligible",
        "reliability_label",
        "window_fingerprint",
        "rejection_reason",
    ],
    "fred_macro_impact_report.csv": [
        "run_id",
        "asset_id",
        "series_id",
        "series_name",
        "source_status",
        "first_available_date",
        "last_available_date",
        "n_observations",
        "missing_pct",
        "release_lag_days",
        "feature_name",
        "information_coefficient",
        "ic_p_value",
        "coverage_pass",
        "stability_pass",
        "used_in_candidate_sets",
        "notes",
    ],
    "macro_candidate_impact_report.csv": [
        "run_id",
        "asset_id",
        "horizon",
        "window_type",
        "candidate_feature_set",
        "model_name",
        "n_features",
        "n_samples",
        "directional_accuracy",
        "balanced_accuracy",
        "brier_score",
        "calibration_error",
        "tc_adjusted_return",
        "sharpe",
        "max_drawdown",
        "bootstrap_ci_low",
        "bootstrap_ci_high",
        "permutation_p_value",
        "beats_buy_hold",
        "beats_momentum_30d",
        "beats_momentum_90d",
        "beats_random_baseline",
        "promotion_decision",
        "rejection_reason",
    ],
    "fred_vs_fallback_summary.csv": [
        "run_id",
        "asset_id",
        "fred_api_status",
        "fallback_used",
        "selected_model_before",
        "selected_model_after",
        "accuracy_before",
        "accuracy_after",
        "accuracy_delta",
        "best_macro_candidate",
        "best_macro_candidate_accuracy",
        "promotion_changed",
        "notes",
    ],
}

REQUIRED_CSV_OUTPUTS = list(OUTPUT_SCHEMAS.keys())
REQUIRED_OUTPUT_FILES = REQUIRED_CSV_OUTPUTS + ["run_manifest.json"]

ALLOWED_DATA_STATUSES = {"worked", "failed", "skipped", "unavailable"}
ALLOWED_RELIABILITY_LABELS = {"High confidence", "Medium confidence", "Low confidence"}


class SchemaError(ValueError):
    pass


def empty_output_frame(filename: str) -> pd.DataFrame:
    return pd.DataFrame(columns=OUTPUT_SCHEMAS[filename])


def empty_diagnostic_frame(filename: str) -> pd.DataFrame:
    return pd.DataFrame(columns=DIAGNOSTIC_OUTPUT_SCHEMAS[filename])


def validate_frame(filename: str, frame: pd.DataFrame) -> None:
    schema = OUTPUT_SCHEMAS.get(filename) or DIAGNOSTIC_OUTPUT_SCHEMAS.get(filename)
    if schema is None:
        raise SchemaError(f"Unknown output schema: {filename}")
    missing = [col for col in schema if col not in frame.columns]
    if missing:
        raise SchemaError(f"{filename} is missing required columns: {', '.join(missing)}")

    if filename == "data_availability.csv":
        invalid = sorted(set(frame["status"].dropna().astype(str)) - ALLOWED_DATA_STATUSES)
        if invalid:
            raise SchemaError(f"data_availability.csv has invalid statuses: {', '.join(invalid)}")

    if "reliability_label" in frame.columns:
        invalid = sorted(set(frame["reliability_label"].dropna().astype(str)) - ALLOWED_RELIABILITY_LABELS)
        if invalid:
            raise SchemaError(f"{filename} has invalid reliability labels: {', '.join(invalid)}")


def write_schema_csv(filename: str, frame: pd.DataFrame, output_dir: Path) -> Path:
    validate_frame(filename, frame)
    schema = OUTPUT_SCHEMAS.get(filename) or DIAGNOSTIC_OUTPUT_SCHEMAS[filename]
    ordered = frame.reindex(columns=schema)
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / filename
    ordered.to_csv(path, index=False)
    return path


def write_diagnostic_csv(filename: str, frame: pd.DataFrame, output_dir: Path) -> Path:
    return write_schema_csv(filename, frame, output_dir / "csv")


def validate_output_file(output_dir: Path, filename: str) -> None:
    path = output_dir / filename
    if not path.exists():
        raise SchemaError(f"Missing required output file: {path}")
    if filename.endswith(".csv"):
        validate_frame(filename, pd.read_csv(path))


def validate_output_dir(output_dir: Path, required: Iterable[str] = REQUIRED_OUTPUT_FILES) -> None:
    for filename in required:
        validate_output_file(output_dir, filename)


def validate_diagnostic_output_dir(output_dir: Path) -> None:
    diagnostic_dir = output_dir / "csv"
    for filename in DIAGNOSTIC_OUTPUT_SCHEMAS:
        validate_output_file(diagnostic_dir, filename)
